language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- 2.7
- 2.6.5 # explicit branch used for deploying docs
- ruby-head
- jruby
branches:
  only:
    - master
    - /^v[0-9]/
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby
before_install: gem install bundler
before_deploy: bundle exec yard
deploy:
  - provider: pages
    local-dir: doc
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
      ruby: 2.6.5
  - provider: rubygems
    gem: amadeus
    email: developer@amadeus.com
    on:
      tags: true
      rvm: 2.6.5
    api_key: $RUBYGEMS_API_KEY
